version: '3.5'

services:
  node1:
    build:
      context: ../
      dockerfile: ./Docker/node/Dockerfile
    restart: always
    image: hogwild/node1
    environment:
      - PORT=50052 # be careful and fix it in the package
  node2:
      build:
        context: ../
        dockerfile: ./Docker/node/Dockerfile/
      restart: always
      image: hogwild/node2
      environment:
        - PORT=50053

  coordinator:
    build:
      context: ../
      dockerfile: ./Docker/coordinator/Dockerfile
    restart: always
    image: hogwild/coordinator
    command:
      - --loglevel warning
    environment:
      - PORT=50051