---
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service-roman
  labels:
    app: coordinator-service-roman
spec:
  ports:
    - port: 80
      name: coordinator-roman
  clusterIP: None
  selector:
    app: coordinator-service-roman
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator-roman
  labels:
    app: coordinator-service-roman
spec:
  serviceName: "coordinator-service-roman"
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: coordinator-service-roman
  replicas: 1
  template:
    metadata:
      labels:
        app: coordinator-service-roman
    spec:
      containers:
        - name: coordinator-service-roman
          image: liabifano/hogwild:latest
          env:
            - name: N_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config-roman
                  key: replicas
            - name: RUNNING_MODE
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config-roman
                  key: running_mode
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config-roman
                  key: data_path
            - name: WHERE
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config-roman
                  key: running_where
          ports:
            - containerPort: 80
              name: coordinator-roman
          command: ["python", "hogwild-python/src/hogwild/super_coordinator.py"]
          volumeMounts:
            - name: shared-volume
              mountPath: /data
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cs449g9-scratch